### ISSUE TITLE
Setup separate test and live environments

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#46]
2 digitalocean droplets will be used. Client's droplet is the live environment, ours is test environment. Test environment must automatically update itself from the repo.

**Comment by AndreasGP** [comment]
Estimated 6 man-hours.

**Comment by Murfin** [comment]
Estimated 6 man-hours.

**Comment by githubERIK** [comment]
It took more than 10 man-hours to set up, because initially there were conflicts between different environments.


Continuous Integration. There is a CI environment present. There is a trace that the CI processes have been running for at least a week. The environment at minimum monitors the VCS in use, checks out the new code, builds it and deploys the application. In case of the errors it reports the errors to the team.

**Comment by githubERIK** [comment]
Added more info for mentor.
[072cdd1](https://github.com/vladislavivanistsev/SuperCap/wiki/_CI/072cdd140a5e06da93bd83e4f26d49ca77f54534)
[Up-to-date page](https://github.com/vladislavivanistsev/SuperCap/wiki/_CI)
